/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldcupRouteImport } from './routes/worldcup'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapWorldcupDotxmlRouteImport } from './routes/sitemap-worldcup[.]xml'
import { Route as SitemapToolsDotxmlRouteImport } from './routes/sitemap-tools[.]xml'
import { Route as SitemapPostsDotxmlRouteImport } from './routes/sitemap-posts[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as ToolsTranslateRouteImport } from './routes/tools.translate'
import { Route as ToolsSummarizeRouteImport } from './routes/tools.summarize'
import { Route as ToolsSeoRouteImport } from './routes/tools.seo'
import { Route as ToolsImageRouteImport } from './routes/tools.image'
import { Route as ToolsIdeasRouteImport } from './routes/tools.ideas'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiToolsTextRouteImport } from './routes/api/tools/text'
import { Route as ApiToolsImageRouteImport } from './routes/api/tools/image'
import { Route as AuthenticatedAdminWorldcupRouteImport } from './routes/_authenticated/admin/worldcup'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin/tools'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin/posts'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const WorldcupRoute = WorldcupRouteImport.update({
  id: '/worldcup',
  path: '/worldcup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapWorldcupDotxmlRoute = SitemapWorldcupDotxmlRouteImport.update({
  id: '/sitemap-worldcup.xml',
  path: '/sitemap-worldcup.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapToolsDotxmlRoute = SitemapToolsDotxmlRouteImport.update({
  id: '/sitemap-tools.xml',
  path: '/sitemap-tools.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPostsDotxmlRoute = SitemapPostsDotxmlRouteImport.update({
  id: '/sitemap-posts.xml',
  path: '/sitemap-posts.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTranslateRoute = ToolsTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSummarizeRoute = ToolsSummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSeoRoute = ToolsSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsImageRoute = ToolsImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsIdeasRoute = ToolsIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => ToolsRoute,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiToolsTextRoute = ApiToolsTextRouteImport.update({
  id: '/api/tools/text',
  path: '/api/tools/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsImageRoute = ApiToolsImageRouteImport.update({
  id: '/api/tools/image',
  path: '/api/tools/image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminWorldcupRoute =
  AuthenticatedAdminWorldcupRouteImport.update({
    id: '/worldcup',
    path: '/worldcup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap-tools.xml': typeof SitemapToolsDotxmlRoute
  '/sitemap-worldcup.xml': typeof SitemapWorldcupDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/worldcup': typeof WorldcupRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/posts/$id': typeof PostsIdRoute
  '/tools/ideas': typeof ToolsIdeasRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/seo': typeof ToolsSeoRoute
  '/tools/summarize': typeof ToolsSummarizeRoute
  '/tools/translate': typeof ToolsTranslateRoute
  '/posts/': typeof PostsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/worldcup': typeof AuthenticatedAdminWorldcupRoute
  '/api/tools/image': typeof ApiToolsImageRoute
  '/api/tools/text': typeof ApiToolsTextRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap-tools.xml': typeof SitemapToolsDotxmlRoute
  '/sitemap-worldcup.xml': typeof SitemapWorldcupDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/worldcup': typeof WorldcupRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/posts/$id': typeof PostsIdRoute
  '/tools/ideas': typeof ToolsIdeasRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/seo': typeof ToolsSeoRoute
  '/tools/summarize': typeof ToolsSummarizeRoute
  '/tools/translate': typeof ToolsTranslateRoute
  '/posts': typeof PostsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/admin/worldcup': typeof AuthenticatedAdminWorldcupRoute
  '/api/tools/image': typeof ApiToolsImageRoute
  '/api/tools/text': typeof ApiToolsTextRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-posts.xml': typeof SitemapPostsDotxmlRoute
  '/sitemap-tools.xml': typeof SitemapToolsDotxmlRoute
  '/sitemap-worldcup.xml': typeof SitemapWorldcupDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/worldcup': typeof WorldcupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/posts/$id': typeof PostsIdRoute
  '/tools/ideas': typeof ToolsIdeasRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/seo': typeof ToolsSeoRoute
  '/tools/summarize': typeof ToolsSummarizeRoute
  '/tools/translate': typeof ToolsTranslateRoute
  '/posts/': typeof PostsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/admin/worldcup': typeof AuthenticatedAdminWorldcupRoute
  '/api/tools/image': typeof ApiToolsImageRoute
  '/api/tools/text': typeof ApiToolsTextRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/sitemap-pages.xml'
    | '/sitemap-posts.xml'
    | '/sitemap-tools.xml'
    | '/sitemap-worldcup.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/worldcup'
    | '/admin'
    | '/favorites'
    | '/posts/$id'
    | '/tools/ideas'
    | '/tools/image'
    | '/tools/seo'
    | '/tools/summarize'
    | '/tools/translate'
    | '/posts/'
    | '/tools/'
    | '/admin/analytics'
    | '/admin/posts'
    | '/admin/tools'
    | '/admin/worldcup'
    | '/api/tools/image'
    | '/api/tools/text'
    | '/admin/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/sitemap-pages.xml'
    | '/sitemap-posts.xml'
    | '/sitemap-tools.xml'
    | '/sitemap-worldcup.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/worldcup'
    | '/favorites'
    | '/posts/$id'
    | '/tools/ideas'
    | '/tools/image'
    | '/tools/seo'
    | '/tools/summarize'
    | '/tools/translate'
    | '/posts'
    | '/tools'
    | '/admin/analytics'
    | '/admin/posts'
    | '/admin/tools'
    | '/admin/worldcup'
    | '/api/tools/image'
    | '/api/tools/text'
    | '/admin'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/privacy'
    | '/sitemap-pages.xml'
    | '/sitemap-posts.xml'
    | '/sitemap-tools.xml'
    | '/sitemap-worldcup.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/tools'
    | '/worldcup'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/posts/$id'
    | '/tools/ideas'
    | '/tools/image'
    | '/tools/seo'
    | '/tools/summarize'
    | '/tools/translate'
    | '/posts/'
    | '/tools/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/worldcup'
    | '/api/tools/image'
    | '/api/tools/text'
    | '/_authenticated/admin/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapPostsDotxmlRoute: typeof SitemapPostsDotxmlRoute
  SitemapToolsDotxmlRoute: typeof SitemapToolsDotxmlRoute
  SitemapWorldcupDotxmlRoute: typeof SitemapWorldcupDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WorldcupRoute: typeof WorldcupRoute
  PostsIdRoute: typeof PostsIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ApiToolsImageRoute: typeof ApiToolsImageRoute
  ApiToolsTextRoute: typeof ApiToolsTextRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worldcup': {
      id: '/worldcup'
      path: '/worldcup'
      fullPath: '/worldcup'
      preLoaderRoute: typeof WorldcupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-worldcup.xml': {
      id: '/sitemap-worldcup.xml'
      path: '/sitemap-worldcup.xml'
      fullPath: '/sitemap-worldcup.xml'
      preLoaderRoute: typeof SitemapWorldcupDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-tools.xml': {
      id: '/sitemap-tools.xml'
      path: '/sitemap-tools.xml'
      fullPath: '/sitemap-tools.xml'
      preLoaderRoute: typeof SitemapToolsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-posts.xml': {
      id: '/sitemap-posts.xml'
      path: '/sitemap-posts.xml'
      fullPath: '/sitemap-posts.xml'
      preLoaderRoute: typeof SitemapPostsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/translate': {
      id: '/tools/translate'
      path: '/translate'
      fullPath: '/tools/translate'
      preLoaderRoute: typeof ToolsTranslateRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/summarize': {
      id: '/tools/summarize'
      path: '/summarize'
      fullPath: '/tools/summarize'
      preLoaderRoute: typeof ToolsSummarizeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/seo': {
      id: '/tools/seo'
      path: '/seo'
      fullPath: '/tools/seo'
      preLoaderRoute: typeof ToolsSeoRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/image': {
      id: '/tools/image'
      path: '/image'
      fullPath: '/tools/image'
      preLoaderRoute: typeof ToolsImageRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ideas': {
      id: '/tools/ideas'
      path: '/ideas'
      fullPath: '/tools/ideas'
      preLoaderRoute: typeof ToolsIdeasRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/tools/text': {
      id: '/api/tools/text'
      path: '/api/tools/text'
      fullPath: '/api/tools/text'
      preLoaderRoute: typeof ApiToolsTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/image': {
      id: '/api/tools/image'
      path: '/api/tools/image'
      fullPath: '/api/tools/image'
      preLoaderRoute: typeof ApiToolsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/worldcup': {
      id: '/_authenticated/admin/worldcup'
      path: '/worldcup'
      fullPath: '/admin/worldcup'
      preLoaderRoute: typeof AuthenticatedAdminWorldcupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminWorldcupRoute: typeof AuthenticatedAdminWorldcupRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
    AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
    AuthenticatedAdminWorldcupRoute: AuthenticatedAdminWorldcupRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ToolsRouteChildren {
  ToolsIdeasRoute: typeof ToolsIdeasRoute
  ToolsImageRoute: typeof ToolsImageRoute
  ToolsSeoRoute: typeof ToolsSeoRoute
  ToolsSummarizeRoute: typeof ToolsSummarizeRoute
  ToolsTranslateRoute: typeof ToolsTranslateRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsIdeasRoute: ToolsIdeasRoute,
  ToolsImageRoute: ToolsImageRoute,
  ToolsSeoRoute: ToolsSeoRoute,
  ToolsSummarizeRoute: ToolsSummarizeRoute,
  ToolsTranslateRoute: ToolsTranslateRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapPostsDotxmlRoute: SitemapPostsDotxmlRoute,
  SitemapToolsDotxmlRoute: SitemapToolsDotxmlRoute,
  SitemapWorldcupDotxmlRoute: SitemapWorldcupDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WorldcupRoute: WorldcupRoute,
  PostsIdRoute: PostsIdRoute,
  PostsIndexRoute: PostsIndexRoute,
  ApiToolsImageRoute: ApiToolsImageRoute,
  ApiToolsTextRoute: ApiToolsTextRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
